//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsianRest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CocktailCard
    {
        public int ID { get; set; }
        public string MealName { get; set; }
        public string Price { get; set; }
        public string Info { get; set; }
    }
}
